# Generated by Django 2.2.4 on 2020-07-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='books_authors', to='books_app.Book'),
        ),
    ]
